### ISSUE TITLE
undefined method `server' for Arask::Railtie:Class (NoMethodError)

### ISSUE THREAD

**Issue by georgecavalcanti** [Ebbe/arask#26]
Hello, i tried use gem, but after running docker container bundle install, rails return error:

`method_missing': undefined method `server' for Arask::Railtie:Class (NoMethodError).

i am using:
- Rails 6.0.0
- Arask 1.2.5

**Comment by Ebbe** [comment]
Sorry. I can see that my code does not work on rails 6.0.0. It does work with older or from 6.1.0 and up. You could upgrade for a fix now. I'll release an update later.
